{% set name = "graphene-sqlalchemy" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2b1a9cf4ed44aec78140605f38061a79b51be5902400d10c3d19b2cf64046215

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - promise
    - graphene
    - sqlalchemy
    - six
    - singledispatch

test:
  imports:
    - graphene_sqlalchemy

about:
  home: https://github.com/graphql-python/graphene-sqlalchemy
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Graphene SQLAlchemy integration
  doc_url: http://docs.graphene-python.org/projects/sqlalchemy/en/latest/
  dev_url: https://github.com/graphql-python/graphene-sqlalchemy

extra:
  recipe-maintainers:
    - mcs07
